In [1]:
import numpy as np
import pandas as pd

In [ ]:
#sklearn
# Linear Regression Model

In [2]:
df= pd.read_csv('iris.csv')
df

sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [3]:
#y=ax+c
#:rain #testing   supervised ML
#80:20
df['variety'].value_counts()

Setosa        50
Versicolor    50
Virginica     50
Name: variety, dtype: int64

In [5]:
x=df.iloc[:,0:4].values # filter Independent variable
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [6]:
y=df.iloc[:,4].values  # filter dependent variable
y

array(['Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolo

In [ ]:
#convert Y in numbers encoding


In [7]:
from sklearn.preprocessing import LabelEncoder

In [8]:
labelencoder_y= LabelEncoder()

In [9]:
y=labelencoder_y.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
from sklearn.model_selection import train_test_split 

In [11]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [12]:
x_train


array([[5.7, 2.8, 4.5, 1.3],
       [7.7, 3. , 6.1, 2.3],
       [7.2, 3.6, 6.1, 2.5],
       [5.1, 3.4, 1.5, 0.2],
       [6. , 3.4, 4.5, 1.6],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.9, 0.4],
       [7.6, 3. , 6.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [6.3, 2.5, 5. , 1.9],
       [5.7, 2.6, 3.5, 1. ],
       [4.8, 3. , 1.4, 0.1],
       [5.4, 3. , 4.5, 1.5],
       [6.1, 3. , 4.6, 1.4],
       [5.4, 3.7, 1.5, 0.2],
       [5.5, 2.6, 4.4, 1.2],
       [6.7, 3. , 5. , 1.7],
       [6.4, 2.7, 5.3, 1.9],
       [6.7, 3.1, 4.4, 1.4],
       [5.1, 3.7, 1.5, 0.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.1, 3. , 4.9, 1.8],
       [6. , 2.2, 4. , 1. ],
       [5.5, 3.5, 1.3, 0.2],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.8, 1.5, 0.3],
       [6.5, 3. , 5.5, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [6.6, 3. , 4.4, 1.4],
       [5.1, 2.5, 3. , 1.1],
       [5.1, 3.5, 1.4, 0.3],
       [7.2, 3.2, 6. , 1.8],
       [4.3, 3. , 1.1, 0.1],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 3

In [13]:
x_train.size

420

In [14]:
x_test.size

180

In [15]:
y_train.size

105

In [16]:
y_test.size

45

In [17]:
from sklearn.linear_model import LogisticRegression

In [18]:
logmodel=LogisticRegression()
logmodel.fit(x_train,y_train)

/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [19]:
y_pred= logmodel.predict(x_test)

In [20]:
y_pred
np.sort(y_pred)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2])

In [21]:
y_test
np.sort(y_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2])

In [22]:
from sklearn.metrics import confusion_matrix

In [23]:
confusion_matrix(y_test,y_pred)

array([[14,  0,  0],
       [ 0, 12,  0],
       [ 0,  3, 16]])

In [24]:
(28/30)*100

93.33333333333333

In [25]:
logmodel.score(x_test,y_test)

0.9333333333333333

In [26]:
from sklearn.neighbors import KNeighborsClassifier  

In [27]:
classifier_knn= KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2) # distance name


In [28]:
classifier_knn.fit(x_train,y_train) # model training 70:30

KNeighborsClassifier()

In [29]:
y_pred_knn=classifier_knn.predict(x_test)

In [30]:
y_pred_knn

array([2, 1, 0, 1, 2, 1, 1, 2, 0, 2, 0, 2, 2, 2, 2, 2, 1, 2, 1, 0, 1, 2,
       2, 0, 0, 0, 1, 1, 0, 2, 2, 0, 1, 0, 1, 2, 1, 0, 0, 2, 0, 0, 1, 2,
       1])

In [31]:
from sklearn.metrics import confusion_matrix


In [32]:
confusion_matrix(y_test,y_pred_knn)

array([[14,  0,  0],
       [ 0, 12,  0],
       [ 0,  2, 17]])

In [33]:
classifier_knn.score(x_test,y_test)

0.9555555555555556